//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Soap_Service_Test")]
    public partial class Order : object
    {
        
        private OrderService.Address DeliveryAddressField;
        
        private string DescriptionField;
        
        private double DiscountField;
        
        private int OrderNoField;
        
        private System.DateTime OrderedDateField;
        
        private string TypeField;
        
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrderService.Address DeliveryAddress
        {
            get
            {
                return this.DeliveryAddressField;
            }
            set
            {
                this.DeliveryAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNo
        {
            get
            {
                return this.OrderNoField;
            }
            set
            {
                this.OrderNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderedDate
        {
            get
            {
                return this.OrderedDateField;
            }
            set
            {
                this.OrderedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Soap_Service_Test")]
    public partial class Address : object
    {
        
        private string CityField;
        
        private string CountryField;
        
        private string NameField;
        
        private string StreetAddress1Field;
        
        private string StreetAddress2Field;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress1
        {
            get
            {
                return this.StreetAddress1Field;
            }
            set
            {
                this.StreetAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress2
        {
            get
            {
                return this.StreetAddress2Field;
            }
            set
            {
                this.StreetAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Soap_Service_Test")]
    public partial class FaultInfo : object
    {
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.IOrderService")]
    public interface IOrderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrdersCount", ReplyAction="http://tempuri.org/IOrderService/GetOrdersCountResponse")]
        System.Threading.Tasks.Task<int> GetOrdersCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetByOrderNo", ReplyAction="http://tempuri.org/IOrderService/GetByOrderNoResponse")]
        System.Threading.Tasks.Task<OrderService.Order> GetByOrderNoAsync(int orderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrdersByDate", ReplyAction="http://tempuri.org/IOrderService/GetOrdersByDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OrderService.FaultInfo), Action="http://tempuri.org/IOrderService/GetOrdersByDateFaultInfoFault", Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Soap_Service_Test")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OrderService.Order>> GetOrdersByDateAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrders", ReplyAction="http://tempuri.org/IOrderService/GetOrdersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OrderService.Order>> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrdersByType", ReplyAction="http://tempuri.org/IOrderService/GetOrdersByTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OrderService.FaultInfo), Action="http://tempuri.org/IOrderService/GetOrdersByTypeFaultInfoFault", Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Soap_Service_Test")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OrderService.Order>> GetOrdersByTypeAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/CreateOrder", ReplyAction="http://tempuri.org/IOrderService/CreateOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OrderService.FaultInfo), Action="http://tempuri.org/IOrderService/CreateOrderFaultInfoFault", Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Soap_Service_Test")]
        System.Threading.Tasks.Task<int> CreateOrderAsync(OrderService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/UpdateOrder", ReplyAction="http://tempuri.org/IOrderService/UpdateOrderResponse")]
        System.Threading.Tasks.Task UpdateOrderAsync(OrderService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/RemoveOrder", ReplyAction="http://tempuri.org/IOrderService/RemoveOrderResponse")]
        System.Threading.Tasks.Task<bool> RemoveOrderAsync(int orderNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IOrderServiceChannel : OrderService.IOrderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<OrderService.IOrderService>, OrderService.IOrderService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrderServiceClient() : 
                base(OrderServiceClient.GetDefaultBinding(), OrderServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.basic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OrderServiceClient.GetBindingForEndpoint(endpointConfiguration), OrderServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrderServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrderServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> GetOrdersCountAsync()
        {
            return base.Channel.GetOrdersCountAsync();
        }
        
        public System.Threading.Tasks.Task<OrderService.Order> GetByOrderNoAsync(int orderNo)
        {
            return base.Channel.GetByOrderNoAsync(orderNo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OrderService.Order>> GetOrdersByDateAsync(string date)
        {
            return base.Channel.GetOrdersByDateAsync(date);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OrderService.Order>> GetOrdersAsync()
        {
            return base.Channel.GetOrdersAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OrderService.Order>> GetOrdersByTypeAsync(string type)
        {
            return base.Channel.GetOrdersByTypeAsync(type);
        }
        
        public System.Threading.Tasks.Task<int> CreateOrderAsync(OrderService.Order order)
        {
            return base.Channel.CreateOrderAsync(order);
        }
        
        public System.Threading.Tasks.Task UpdateOrderAsync(OrderService.Order order)
        {
            return base.Channel.UpdateOrderAsync(order);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveOrderAsync(int orderNo)
        {
            return base.Channel.RemoveOrderAsync(orderNo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basic))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64307/OrderService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OrderServiceClient.GetBindingForEndpoint(EndpointConfiguration.basic);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OrderServiceClient.GetEndpointAddress(EndpointConfiguration.basic);
        }
        
        public enum EndpointConfiguration
        {
            
            basic,
        }
    }
}
